# Generated by Django 3.2.18 on 2023-09-13 03:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

def populate_db(apps, schema_editor):
    """ wpisujemy do bazy po kilka kategorii i tagów"""
    category_names = ["ogólna", "nauka", "życie"]                               
    Category = apps.get_model('test_app', 'Category')
    for name in category_names:
        obj = Category(category=name)
        obj.save()

    tag_names = ["blog", "technologia", "plotki","zdrowie","polityka"]   
    colors = ["light green","light blue","pink","yellow","red"]                            
    Tag = apps.get_model('test_app', 'Tag')
    for i in range(0,len(tag_names)):
        obj = Tag(tag=tag_names[i],color = colors[i])
        obj.save()

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('body', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=140)),
                ('color', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=140)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.article')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.category'),
        ),
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(to='test_app.Tag'),
        ),
        migrations.RunPython(populate_db),
    ]
